### ISSUE TITLE
[Typescript] [tsc]: error TS2304: Cannot find name 'Parameters'

### ISSUE THREAD

**Issue by mfaizanse** [express-validator/express-validator#763]
Hi, I am using express-validator@6.1.1. When trying to run tsc I am getting the following error. Looks like the definition for 'Parameters' is missing. Let me know if I need to install any other pkg for definition?

```
node_modules/express-validator/src/middlewares/schema.d.ts:6:15 - error TS2304: Cannot find name 'Parameters'.

6     options?: Parameters<Validators<any>[K]> | Parameters<Validators<any>[K]>[0];
                ~~~~~~~~~~

node_modules/express-validator/src/middlewares/schema.d.ts:6:48 - error TS2304: Cannot find name 'Parameters'.

6     options?: Parameters<Validators<any>[K]> | Parameters<Validators<any>[K]>[0];
                                                 ~~~~~~~~~~

node_modules/express-validator/src/middlewares/schema.d.ts:14:15 - error TS2304: Cannot find name 'Parameters'.

14     options?: Parameters<Sanitizers<any>[K]> | Parameters<Sanitizers<any>[K]>[0];
                 ~~~~~~~~~~

node_modules/express-validator/src/middlewares/schema.d.ts:14:48 - error TS2304: Cannot find name 'Parameters'.

14     options?: Parameters<Sanitizers<any>[K]> | Parameters<Sanitizers<any>[K]>[0];
                                                  ~~~~~~~~~~

error Command failed with exit code 1.
```

Node version: 10.5.0
Typescript version: 3.0.3

**Comment by gustavohenke** [comment]
Hey!
It seems you need to upgrade your TS version.
`Parameters` is a native TS type -- I couldn't find the exact version where it was introduced, but it seems to work with v3.1.6, according to this playground:
https://www.typescriptlang.org/play/index.html?ts=3.1.6#code/GYVwdgxgLglg9mABMOcAUAjAhgJwFyIDOUOMYA5gJSIDeAUHQL4NQCeADgKaIAaiAvIgAKuLAFtOUTjkIAeNlzjBkqAHwBuRAHotiANrFSFALpA
